#!/usr/bin/env python
# -*- coding: utf-8 -*-
#    This file is part of parltrack

#    parltrack is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    parltrack is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.

#    You should have received a copy of the GNU Affero General Public License
#    along with parltrack  If not, see <http://www.gnu.org/licenses/>.

# (C) 2019 by Stefan Marsiske, <parltrack@ctrlc.hu>

buildings={ u"Altiero Spinelli": u'ASP',
            u"Willy Brandt": u'WIB',
            u"Paul-Henri Spaak": u'PHS',
            u"Atrium": u"ATR",
            u"Louise Weiss": u'LOW',
            u"Winston Churchill": u'WIC',
            u'Salvador de Madariaga': u"SDM",
            u"Bât. Altiero Spinelli": u'ASP',
            u"Bât. Willy Brandt": u'WIB',
            u"Bât. Paul-Henri Spaak": u'PHS',
            u"Bât. Atrium": u"ATR",
            u"Bât. Louise Weiss": u'LOW',
            u"Bât. Winston Churchill": u'WIC',
            u'B\xe2t. Salvador de Madariaga': u"SDM",
            }

COUNTRIES = {
    'BE': u'Belgium',
    'BG': u'Bulgaria',
    'CZ': u'Czechia',
    'DK': u'Denmark',
    'DE': u'Germany',
    'EE': u'Estonia',
    'IE': u'Ireland',
    'EL': u'Greece',
    'GR': u'Greece',
    'ES': u'Spain',
    'FR': u'France',
    'IT': u'Italy',
    'CY': u'Cyprus',
    'LV': u'Latvia',
    'LT': u'Lithuania',
    'LU': u'Luxembourg',
    'HU': u'Hungary',
    'MT': u'Malta',
    'NL': u'Netherlands',
    'AT': u'Austria',
    'PL': u'Poland',
    'PT': u'Portugal',
    'RO': u'Romania',
    'SI': u'Slovenia',
    'SK': u'Slovakia',
    'FI': u'Finland',
    'SE': u'Sweden',
    'UK': u'United Kingdom',
    'GB': u'United Kingdom',
    'HR': u'Croatia',
 }

SEIRTNUOC = {'Belgium': u'BE',
             'Bulgaria': u'BG',
             'Czech Republic': u'CZ',
             'Czechia': u'CZ',
             'Denmark': u'DK',
             'Germany': u'DE',
             'Estonia': u'EE',
             'Ireland': u'IE',
             'Greece': u'EL',
             'Spain': u'ES',
             'France': u'FR',
             'Italy': u'IT',
             'Cyprus': u'CY',
             'Latvia': u'LV',
             'Lithuania': u'LT',
             'Luxembourg': u'LU',
             'Hungary': u'HU',
             'Malta': u'MT',
             'Netherlands': u'NL',
             'Austria': u'AT',
             'Poland': u'PL',
             'Portugal': u'PT',
             'Romania': u'RO',
             'Slovenia': u'SI',
             'Slovakia': u'SK',
             'Finland': u'FI',
             'Sweden': u'SE',
             'United Kingdom': u'GB',
             'Croatia': u'HR',
             }

COMMITTEE_MAP={u'AFET': u"Foreign Affairs",
               u'DROI': u"Human Rights",
               u'CLIM': u'Climate Change',
               u'CRIM': u'Organised crime, corruption and money laundering',
               u'TDIP': u'Temporary committee on use of European countries by the CIA',
               u'SEDE': u"Security and Defence",
               u'DEVE': u"Development",
               u'INTA': u"International Trade",
               u'BUDG': u"Budgets",
               u'CONT': u"Budgetary Control",
               u'CODE': u"Conciliation Committee",
               u'ECON': u"Economic and Monetary Affairs",
               u'EMPL': u"Employment and Social Affairs",
               u'ENVI': u"Environment, Public Health and Food Safety",
               u'ITRE': u"Industry, Research and Energy",
               u'IMCO': u"Internal Market and Consumer Protection",
               u'TRAN': u"Transport and Tourism",
               u'REGI': u"Regional Development",
               u"ENER": u"Research, Technological Development and Energy",
               u'AGRI': u"Agriculture and Rural Development",
               u'PECH': u"Fisheries",
               u'CULT': u"Culture and Education",
               u'JURI': u"Legal Affairs",
               u'LIBE': u"Civil Liberties, Justice and Home Affairs",
               u'AFCO': u"Constitutional Affairs",
               u'FEMM': u"Women's Rights and Gender Equality",
               u"BUDE": u"Budgetary Conciliation Committee",
               u"DELE": u"EP Delegation to Conciliation Committee",
               u"EQUI": u"Inquiry committee on the Equitable Life Assurance Society",
               u"FINP": u"Temporary committee on the enlarged Union for 2007-2013",
               u"INST": u"Institutional Affairs",
               u"REGL": u"Rules of Procedure, Verification of Credentials and Immunities",
               u'PETI': u"Petitions",
               u"RELA": u"External Economic Relations",
               u'CRIS': u"Financial, Economic and Social Crisis",
               u'SURE': u"Policy Challenges Committee",
               u"TCOM": u"Temporary committee on the follow-up of recommendations on BSE",
               u'RETT': u"Regional Policy, Transport and Tourism",
               u"PANA": u'Committee of inquiry into money laundering, tax avoidance and tax evasion',
               u"TERR": u'Special Committee on Terrorism',
               u"PEST": u"Special Committee on the Union's authorisation procedure for pesticides",
               u"TAX2": u'Special Committee on Tax Rulings and Other Measures Similar in Nature or Effect (TAXE 2)',
               u"TAX3": u"Special Committee on Financial Crimes, Tax Evasion and Tax Avoidance",
               u"EMIS": u'Committee of Inquiry into Emission Measurements in the Automotive Sector',
               u"TAXE": u'Special Committee on Tax Rulings and Other Measures Similar in Nature or Effect',
               u'ECHE': u"Temporary Committee on ECHELON Interception System",
               u'Foreign Affairs': u'AFET',
               u"Regional Policy, Transport and Tourism": u'RETT',
               u"Committee on Regional Policy, Transport and Tourism": u'RETT',
               u'Foreign Affairs': u'AFET',
               u'Subcommittee on Human Rights': u'DROI',
               u'Human Rights': u'DROI',
               u'Security and Defence': u'SEDE',
               u'Development': u'DEVE',
               u'International Trade': u'INTA',
               u'Budgets': u'BUDG',
               u'Budgetary Control': u'CONT',
               u'Organised crime, corruption and money laundering' : u'CRIM',
               u'Economic and Monetary Affairs': u'ECON',
               u'Employment and Social Affairs': u'EMPL',
               u'Environment, Public Health and Food Safety': u'ENVI',
               u'Industry, Research and Energy': u'ITRE',
               u'Internal Market and Consumer Protection': u'IMCO',
               u'Transport and Tourism': u'TRAN',
               u'Regional Development': u'REGI',
               u'Agriculture and Rural Development': u'AGRI',
               u'Fisheries': u'PECH',
               u'Culture and Education': u'CULT',
               u'Legal Affairs': u'JURI',
               u'Civil Liberties, Justice and Home Affairs': u'LIBE',
               'Civil Liberties, Justice and Home Affairs Libertés civiles, justice et affaires intérieures': 'LIBE',
               u'Constitutional Affairs': u'AFCO',
               u"Women's Rights and Gender Equality": u'FEMM',
               u"Committee on Women's Rights and Gender": u'FEMM',
               u"Women’s Rights and Gender Equality": u'FEMM',
               u"Womens Rights and Gender Equality": u'FEMM',
               u'Petitions': u'PETI',
               u'Financial, Economic and Social Crisis': u'CRIS',
               u'Policy Challenges Committee': u'SURE',
               u'Committee on Foreign Affairs': u'AFET',
               u'Committee on Human Rights': u'DROI',
               u'Committee on Security and Defence': u'SEDE',
               u'Committee on Development': u'DEVE',
               u'Committee on development': u'DEVE',
               u'Special Committee on the Financial, Economic and Social Crisis': u'CRIS',
               u'Special committee on the policy challenges and budgetary resources for a sustainable': u'SURE',
               u'Special committee on the policy challenges and budgetary resources for a sustainable European Union after 2013': u'SURE',
               u'Committee on International Trade': u'INTA',
               u'Committee on Budgets': u'BUDG',
               u'Committee on Budgetary Control': u'CONT',
               u'Committee on Economic and Monetary Affairs': u'ECON',
               u'Committee on Employment and Social Affairs': u'EMPL',
               u"Commission de l'emploi et des affaires sociales": u'EMPL',
               u'Commission des libertés civiles, de la justice et des affaires intérieures': u'LIBE',
               u'Committee on Environment, Public Health and Food Safety': u'ENVI',
               u'Committee on the Environment, Public Health and Food Safety': u'ENVI',
               u'Committee on Industry, Research and Energy': u'ITRE',
               u'Committee on Internal Market and Consumer Protection': u'IMCO',
               u'Committee on the Internal Market and Consumer Protection': u'IMCO',
               u'Committee on Transport and Tourism': u'TRAN',
               u'Committee on Regional Development': u'REGI',
               u'Committee on Agriculture and Rural Development': u'AGRI',
               u'Committee on Agricultural and Rural Development': u'AGRI',
               u'Committee on Committee on Agriculture and Rural Development': u'AGRI',
               u"Commission de l'agriculture et du développement rural": u'AGRI',
               u"Commission du marché intérieur et de la protection des consommateurs": u'IMCO',
               u'Co-Committee on the Internal Market and Consumer Protection': u'IMCO',
               u'COMMITTEE ON THE INTERNAL MARKET AND CONSUMER PROTECTION': u'IMCO',
               u'Committee on Fisheries': u'PECH',
               u'Committee on Culture and Education': u'CULT',
               u'Committee on Legal Affairs': u'JURI',
               u'Committee on Civil Liberties, Justice and Home Affairs': u'LIBE',
               u'Committee on Constitutional Affairs': u'AFCO',
               u"Committee on Women's Rights and Gender Equality": u'FEMM',
               u"Committee on Women’s Rights and Gender Equality": u'FEMM',
               u"Committee on Womens Rights and Gender Equality": u'FEMM',
               u'Committee on Petitions': u'PETI',
               u'Committee on Financial, Economic and Social Crisis': u'CRIS',
               u'Committee on Policy Challenges Committee': u'SURE',
               u"Committee on Constitutional Affairs"                                                                                          : u"AFCO",
               u"Committee on Foreign Affairs"                                                                                                 : u"AFET",
               u"Committee on Agriculture and Rural Development"                                                                               : u"AGRI",
               u"Committee on Budgets"                                                                                                         : u"BUDG",
               u"Temporary Committee on Climate Change"                                                                                        : u"CLIM",
               u"Committee on Budgetary Control"                                                                                               : u"CONT",
               u"Temporary Committee on Organised Crime, Corruption and Money Laundering"                                                      : u"CRIM",
               u"Special Committee on Organised Crime, Corruption and Money Laundering"                                                        : u"CRIM",
               u"Temporary Committee on Financial, Economic and Social Crisis"                                                                 : u"CRIS",
               u"Committee on Culture and Education"                                                                                           : u"CULT",
               u"Committee on Development"                                                                                                     : u"DEVE",
               u"Subcommittee on Human Rights"                                                                                                 : u"DROI",
               u"Temporary Committee on ECHELON Interception System"                                                                           : u"ECHE",
               u"Temporary committee on the Echelon interception system"                                                                       : u"ECHE",
               u"Committee on Economic and Monetary Affairs"                                                                                   : u"ECON",
               u"Committee on Employment and Social Affairs"                                                                                   : u"EMPL",
               u"Committee on Environment, Public Health and Food Safety"                                                                      : u"ENVI",
               u"Committee of Inquiry into the crisis of the Equitable Life Assurance Society"                                                 : u"EQUI",
               u"Temporary Committee Crisis of the Equitable Life Assurance Society"                                                           : u"EQUI",
               u"Committee of Inquiry into BSE (bovine spongiform encephalopathy)"                                                             : u"ESB1",
               u"Temporary committee on the follow-up of recommendations on BSE"                                                               : u"TCOM",
               u"Temporary Committee to Monitor Action taken on BSE Recommendations"                                                           : u"ESB2",
               u"Committee on Women's Rights and Gender Equality"                                                                              : u"FEMM",
               u"Temporary Committee on Foot and Mouth Disease"                                                                                : u"FIAP",
               u"Temporary Committee Policy challenges and budgetary means of the enlarged Union 2007-2013"                                    : u"FINP",
               u'Temporary committee on the enlarged Union for 2007-2013'                                                                      : u"FINP",
               u"Temporary Committee on Policy Challenges and Budgetary Means of the Enlarged Union 2007-2013"                                 : u"FINP",
               u"Temporary Committee on Human Genetics and other New Technologies of Modern Medicine"                                          : u"GENE",
               u"Committee on Internal Market and Consumer Protection"                                                                         : u"IMCO",
               u"Committee on International Trade"                                                                                             : u"INTA",
               u"Committee on Industry, Research and Energy"                                                                                   : u"ITRE",
               u"Committee on Industry, External Trade, Research and Energy"                                                                   : u"ITRE",
               u"Committee on Legal Affairs"                                                                                                   : u"JURI",
               u"Committee on Civil Liberties, Justice and Home Affairs"                                                                       : u"LIBE",
               u"Temporary Committee on Improving Safety at Sea"                                                                               : u"MARE",
               u"Committee on Fisheries"                                                                                                       : u"PECH",
               u"Committee on Petitions"                                                                                                       : u"PETI",
               u"Committee on Regional Development"                                                                                            : u"REGI",
               u"Subcommittee on Security and Defence"                                                                                         : u"SEDE",
               u"Temporary Committees Policy Challenges Committee"                                                                             : u"SURE",
               u"Temporary Committee Alleged use of European countries by the CIA for the transport and illegal detention of prisoners"        : u"TDIP",
               u"Temporary Committee on the alleged use of European countries by the CIA for the transport and illegal detention of prisoners" : u"TDIP",
               u"Committee on Transport and Tourism"                                                                                           : u"TRAN",
               u"Committee of Inquiry into the Community Transit Regime"                                                                       : u"TRANSIT",
               u'Special Committee on Tax Rulings and Other Measures Similar in Nature or Effect'                                              : u"TAXE",
               u'Special Committee on Tax Rulings and Other Measures Similar in Nature or Effect (TAXE 2)'                                     : u"TAX2",
               u"Special Committee on Financial Crimes, Tax Evasion and Tax Avoidance"                                                         : u"TAX3",
               u'Special committee on financial crimes, tax evasion and tax avoidance'                                                         : u"TAX3",
               u'Special committee on tax rulings'                                                                                             : u'TAX2',
               u'Committee of inquiry into money laundering, tax avoidance and tax evasion'                                                    : u"PANA",
               u'Committee of inquiry on emission measurements in the automotive sector'                                                       : u'EMIS',
               u'Special Committee on Terrorism'                                                                                               : u"TERR",
               u'Special committee on terrorism'                                                                                               : u"TERR",
               u'Special Committee on the Union_s authorisation procedure for pesticides'                                                      : u"PEST",
               u"Special Committee on the Union's authorisation procedure for pesticides"                                                      : u"PEST",
               u'Special committee on the Union’s authorisation procedure for pesticides'                                                      : u"PEST",
               u'Special committee on the Unions authorisation procedure for pesticides'                                                      : u"PEST",
               u"Committee on Citizens' Freedoms and Rights, Justice and Home Affairs"                                                         : u"LIBE",
               u"Committee on Foreign Affairs, Human Rights, Common Security and Defence Policy"                                               : u"AFET",
               u"Committee on Foreign Affairs, Security and Defence Policy"                                                                    : u"AFET",
               u'Committee of Inquiry into Emission Measurements in the Automotive Sector'                                                     : u"EMIS",
               u'Committee of Inquiry to investigate alleged contraventions and maladministration in the application of Union law in relation to money laundering, tax avoidance and tax evasion': u'TAX3',
               u'Parliament delegation to Conciliation Committee'                                                                              : u"CODE",
               u"Parliament Delegation to Concilations Committee"                                                                              : u"CODE",
               u'Inquiry committee on the Equitable Life Assurance Society'                                                                    : u'EQUI',
               u'Committee on Development and Cooperation'                                                                                     : u"",
               u'Institutional Affairs'                                                                                                        : u"",
               u'Temporary committee on policy challenges and budgetary means of the enlarged Union 2007-2013'                                 : u"",
               u'Committee on Culture, Youth, Education, the Media and Sport'                                                                  : u"",
               u"Agriculture and Rural Development"                                                             : u"AGRI",
               u"Budgetary Conciliation Committee"                                                              : u"BUDE",
               u"Budgetary Control"                                                                             : u"CONT",
               u"Budgets"                                                                                       : u"BUDG",
               u"Citizens' Freedoms and Rights, Justice and Home Affairs"                                       : u"LIBE",
               u"Civil Liberties and Internal Affairs"                                                          : u"LIBE",
               u"Civil Liberties, Justice and Home Affairs"                                                     : u"LIBE",
               u"Climate Change"                                                                                : u"CLIM",
               u"Constitutional Affairs"                                                                        : u"AFCO",
               u"Culture and Education"                                                                         : u"CULT",
               u"Culture, Youth, Education, Media and Sport"                                                    : u"CULT",
               u"Development and Cooperation"                                                                   : u"DEVE",
               u"Development"                                                                                   : u"DEVE",
               u"EP Delegation to Conciliation Committee"                                                       : u"CODE",
               u"EP Delegation to Conciliation Committee"                                                       : u"DELE",
               u"Economic and Monetary Affairs"                                                                 : u"ECON",
               u"Economic and Monetary Affairs, Industrial Policy"                                              : u"ECON",
               u"Employment and Social Affairs"                                                                 : u"EMPL",
               u"Environment, Public Health and Consumer Protection"                                            : u"ENVI",
               u"Environment, Public Health and Food Safety"                                                    : u"ENVI",
               u"Environment, Public Health, Consumer Policy"                                                   : u"ENVI",
               u"External Economic Relations"                                                                   : u"RELA",
               u"Foreign Affairs"                                                                               : u"AFET",
               u"Foreign Affairs, Human Rights, Common Security, Defense"                                       : u"AFET",
               u"Foreign Affairs, Security and Defense Policy"                                                  : u"AFET",
               u"Industry, External Trade, Research, Energy"                                                    : u"ITRE",
               u"Industry, Research and Energy"                                                                 : u"ITRE",
               u"Inquiry committee on the Equitable Life Assurance Society"                                     : u"EQUI",
               u"Institutional Affairs"                                                                         : u"INST",
               u"Internal Market and Consumer Protection"                                                       : u"IMCO",
               u"International Trade"                                                                           : u"INTA",
               u"Legal Affairs and Internal Market"                                                             : u"JURI",
               u"Legal Affairs"                                                                                 : u"JURI",
               u"Legal Affairs, Citizens' Rights"                                                               : u"JURI",
               u"Petitions"                                                                                     : u"PETI",
               u"Regional Development"                                                                          : u"REGI",
               u"Regional Policy"                                                                               : u"REGI",
               u"Regional Policy, Transport and Tourism"                                                        : u"RETT",
               u"Research, Technological Development and Energy"                                                : u"ENER",
               u"Rules of Procedure, Verification of Credentials and Immunities"                                : u"REGL",
               u"Special committee on EU policy challenges and budgetary resources after 2013"                  : u"SURE",
               u"Special committee on organised crime, corruption and money laundering"                         : u"CRIM",
               u"Special committee on the financial, economic and social crisis"                                : u"CRIS",
               u"Temporary committee on the enlarged Union for 2007-2013"                                       : u"FINP",
               u"Temporary committee on use of European countries by the CIA"                                   : u"TDIP",
               u"Transport and Tourism"                                                                         : u"TRAN",
               u"Women's Rights and Equal Opportunities"                                                        : u"FEMM",
               u"Women's Rights and Gender Equality"                                                            : u"FEMM",
               u"Women's Rights"                                                                                : u"FEMM",
               u"Committee on Agriculture, Fisheries and Food": u"",
               u"Committee on the Verification of Credentials": u"",
               u"Committee on Youth, Culture, Education, the Media and Sport": u"",
               u"Temporary committee of inquiry into the Community Transit System": u"",
               u"Committee on Culture, Youth, Education and the Media": u"",
               u"Committee on the Rules of Procedure, the Verification of Credencials and Immunities": u"",
               u"Committee on Transports and Tourism": u"",
               u"Committee on Youth, Culture, Education, Information and Sport": u"",
               u"Subcommittee on Fisheries": u"",
               u"Temporary committee instructed to monitor the action taken on the recommendations made concerning BSE (bovine spongiform encephalopathy)": u"",
               u"Temporary committee of inquiry into BSE (bovine spongiform encephalopathy)": u"",
               u"Committee on Foreign Affairs and Security": u"",
               u"Committee on Regional Policy, Regional Planning and Relations with Regional and Local Authorities": u"",
               u"Subcommittee on Security and Disarmament": u"",
               u"Temporary committee on employment": u"",
               u"Committee on Regional Policy": u"",
               u"Committee on Energy, Research and Technology": u"",
               u"Committee on Social Affairs and Employment": u"",
               u"Subcommittee on Monetary Affairs": u"",
               u"Temporary committee on improving safety at sea": u"",
               u"Committee on Regional Policy and Regional Planning": u"",
               u"Committee on the Rules of Procedure, the Verification of Credentials and Immunities": u"",
               u"Temporary committee on foot and mouth disease": u"",
               u"Committee on Agriculture, Fisheries and Rural Development": u"",
               u"Committee on Social Affairs, Employment and the Working Environment": u"",
               u"Political Affairs Committee": u"",
               u"Committee on Civil Liberties and Internal Affairs": u"",
               u"Committee on External Economic Relations": u"",
               u"Committee on Women's Rights": u"",
               u"Temporary committee on human genetics and other new technologies in modern medicine": u"",
               u"Committee on Research, Technological Development and Energy": u"",
               u"Committee on Legal Affairs and the Internal Market": u"",
               u"Committee on Legal Affairs and Citizens' Rights": u"",
               u"Committee on Institutional Affairs": u"",
               u"Committee on Women's Rights and Equal Opportunities": u"",
               u"Committee on Economic and Monetary Affairs and Industrial Policy": u"",
               u"Committee on the Environment, Public Health and Consumer Protection": u"ENVI",
               u"Committee on the Environment, Public Health and Consumer Policy": u"",
               u"Special Committee on the Union_s authorisation procedure for pesticides": u"",
}

ORGMAPS=[('Committee o', 'Committees'),
        ('Temporary committee ', 'Committees'),
        ('Temporary Committee ', 'Committees'),
        ('Subcommittee on ', 'Committees'),
        ('Special Committee ', 'Committees'),
        ('Special committee ', 'Committees'),
        ('Legal Affairs Committee', 'Committees'),
        ('Political Affairs Committee', 'Committees'),
        ('Delegation','Delegations'),
        ('Members from the European Parliament to the Joint ', 'Delegations'),
        ('Membres fron the European Parliament to the ', 'Delegations'),
        ('Conference of ', 'Staff'),
        ("Parliament's Bureau", 'Staff'),
        ('European Parliament', 'Staff'),
        ('Quaestors', 'Staff'),]

GROUP_MAP={ u"Confederal Group of the European United Left - Nordic Green Left": u'GUE/NGL',
            u"European United Left - Nordic Green Left": u'GUE/NGL',
            u'European United Left - Nordic\xa0Green\xa0Left': u"GUE/NGL",
            u"Confederal Group of the European United Left-Nordic Green Left": u'GUE/NGL',
            u'Confederal Group of the European United Left / Nordic Green Left': u'GUE/NGL',
            u'Confederal Group of the European United Left/Nordic Green Left': u'GUE/NGL',
            u'European United Left/Nordic Green Left': u"GUE/NGL",
            u'Identity, Tradition, Sovereignty': u'ITS',
            u'Confederal Group of the European United Left': u'GUE/NGL',
            u"European Conservatives and Reformists": u'ECR',
            u'European Conservatives and Reformists Group': u'ECR',
            u"Europe of freedom and democracy Group": u'EFD',
            u'Europe of Freedom and Democracy': u"EFD",
            u'Europe of Freedom and Direct Democracy Group': u"EFDD",
            u'Europe of Freedom and Direct Democracy': u"EFDD",
            u'Europe of Freedom and Democracy Group': u'EFD',
            u'Europe of freedom and direct democracy Group': u'EFD',
            u"Group of the Alliance of Liberals and Democrats for Europe": u'ALDE',
            u'Liberal and Democratic Reformist Group': u'LDR',
            u'Group Union for Europe': u'UFE',
            u'European Democratic Group': u'EDG',
            u'Liberal and Democratic Group': u'ALDE',
            u'Technical Group of the European Right': u'DR',
            u'Group of the European Radical Alliance': u'ERA',
            u'Socialist Group': u'SG',
            u'Rainbow Group in the European Parliament': u'RBW',
            u'Group of the European Right': u'ER',
            u'Group of Independents for a Europe of Nations': u'ER',
            u'Independents for a Europe of Nations': u'ER',
            u'Left Unity': u'LU',
            u'Group for the European United Left': u'GUE',
            u'Group of the European Democratic Alliance': u'EDA',
            u"Group of the Greens/European Free Alliance": u"Verts/ALE",
            u'The Greens/European Free Alliance': u"Verts/ALE",
            u'Greens/European Free Alliance': u"Verts/ALE",
            u"Group of the Progressive Alliance of Socialists and Democrats in the European Parliament": u"S&D",
            u'Group for a Europe of Democracies and Diversities': u'EDD',
            u'Europe of Democracies and Diversities': u'EDD',
            u'Group of the European Liberal Democrat and Reform Party': u'ELDR',
            u'European Liberal Democrat and Reform Party': u'ELDR',
            u'European Liberal Democratic and Reformist Party': u"ELDR",
            u'Union for Europe Group': u"UFE",
            u'Group of the European Liberal, Democrat and Reform Party': u'ELDR',
            'Identity and Democracy': 'ID',
            'Identity and Democracy Group': 'ID',
            u'Group indépendence/Démocratie': u'IND/DEM',
            u'Independence/Democracy Group': u'IND/DEM',
            u'Independence and democracy': u'IND/DEM',
            u'Non-attached Members': 'NA',
            u'Non-attached members':  'NA',
            u'Non-attached members': 'NA',
            u'Non-attached': 'NA',
            'Renew Europe Group': "RE",
            'Renew Europe': "RE",
            u'Identity, Tradition and Sovereignty Group': u'ITS',
            u"Group of the European People's Party (Christian Democrats) and European Democrats": u'PPE-DE',
            u"European People's Party (Christian Democrats) and European Democrats": u"PPE-DE",
            u"European People's Party (Christian Democrats) and European Democrats": u"PPE-DE",
            u"European People's Party (Christian Democrats)": u"PPE",
            u"European People's Party (Christian Democrats)": u"PPE",
            u"Group of European People's Party": u"EPP",
            u"Group of the European People's Party (Christian Democrats)": u'PPE',
            u"European People's Party (Christian Democrats)": u'PPE',
            u"Group of the European People's Party (Christian-Democratic Group)": u"PPE",
            u'Group of the Party of European Socialists': u'PSE',
            u'Socialist Group in the European Parliament': u'PSE',
            u'Technical Group of Independent Members': u'TDI',
            u'Group indépendence/Démocratie': u'UEN',
            u'Union for a Europe of Nations Group': u'UEN',
            u'Europe of Nations Group (Coordination Group)': u'UEN',
            u'Europe of Nations (Coordination Group)': u'UEN',
            u'Union for Europe of the Nations Group': u'UEN',
            u'Union for Europe of the Nations': u"UEN",
            u'Group of the Greens / European Free Alliance': u'Verts/ALE',
            u'Greens/European Free Alliance': u'Verts/ALE',
            u'The Green Group in the European Parliament': u'Verts/ALE',
            u'Green Group in the European Parliament': u"Verts/ALE",
            u'Greens/EFA': u'Verts/ALE',
            u'Christian Democratic Group': u'CD',
            u'Christian Democratic Group': u'CD',
            u'European Conservatives': u'C',
            u'European Democrats': u'ED',
            u'European People\'s Party': u'EPP',
            u'Forza Europa': u'FE',
            u'European People\'s Party–European Democrats': u'EPP-ED',
            u'Socialist Group': u'S',
            u'Socialist Group': u'SOC',
            u'Party of European Socialists': u'PES',
            u'Progressive Alliance of Socialists and Democrats': u'S&D',
            u'Liberal Group': u'L',
            u'Liberal and Democratic Group': u'LD',
            u'Liberal and Democratic Reformist Group': u'LDR',
            u'European Liberal Democratic and Reform Party': u'ELDR',
            u'European Radical Alliance': u'ERA',
            u'Alliance of Liberals and Democrats for Europe': u'ALDE',
            u'European Democratic Union': u'UDE',
            u'European Democratic Union Group': u'UDE',
            u'European Progressive Democrats': u'EPD',
            u'European Democratic Alliance': u'EDA',
            u'Group Union for Europe': u'UFE',
            u'Union for Europe of the Nations': u'UEN',
            u'Rainbow Group': u'RBW',
            u'Rainbow Group': u'RBW',
            u'The Green Group': u'G',
            u'Communists and Allies': u'COM',
            u'Communist and Allies Group (SF, Ind. Sin.)': u'COM',
            u'European United Left': u'EUL',
            u'Left Unity': u'LU',
            u'European United Left': u'EUL',
            u'European United Left–Nordic Green Left': u'EUL/NGL',
            u'Technical Group of Independent Members - mixed group': u'TGI',
            u'Communist and Allies Group': u'COM',
            u"Rainbow Group: Federation of the Green-Alternative European Links, Agelev-Ecolo, the Danish People's Movement against Membership of the European Community and the European Free Alliance in the European Parliament": u'RBW',
            u'Group for the Technical Coordination and Defence of Indipendent Groups and Members': u'CDI',
            u'Group for the Technical Coordination and Defence of Independent Groups and Members': u'CDI',
            u'Technical Coordination and Defence of Independent Groups and Members': u'CDI',
            u'Forza Europa Group': u'FE',
            u'Christian-Democratic Group': u'CD',
            u"Christian-Democratic Group (Group of the European People's Party)": u'CD',
            u'European Conservative Group': u'C',
            u'Group of European Progressive Democrats': u'DEP',
            u'Europe of Nations and Freedom Group': u'ENF',
            u'Europe of Nations and Freedom': u"ENF",
            }
GROUPIDS=[]
for item in GROUP_MAP.values():
    if type(item)==list:
        GROUPIDS.extend(item)
    else:
        GROUPIDS.append(item)

DELEGATIONS={
    "Armenia, Azerbaijan, Georgia": "AAG",
    "Bulgaria": "BULG",
    "Cyprus": "CYPR",
    "Czech Republic": "CZEC",
    "Afghanistan": "D-AF",
    "Delegation for relations with Afghanistan": "D-AF",
    "Delegation to the EU-Albania Stabilisation and Association Parliamentary Committee": "D-AL",
    "Delegation for relations with the Federative Republic of Brazil": "D-BR",
    "Belarus": "D-BY",
    "Delegation for relations with Belarus": "D-BY",
    "Canada": "D-CA",
    "Delegation for relations with Canada": "D-CA",
    "Delegation to the EU-Chile Joint Parliamentary Committee": "D-CL",
    "EU-Chile": "D-CL",
    "Delegation for relations with the People's Republic of China": "D-CN",
    "People's Republic of China": "D-CN",
    "EU-Croatia": "D-HR",
    "Delegation to the EU-Croatia Joint Parliamentary Committee": "D-HR",
    "Delegation for relations with Israel": "D-IL",
    "Israel": "D-IL",
    "Delegation for relations with India": "D-IN",
    "India": "D-IN",
    "Delegation for relations with Iraq": "D-IQ",
    "Iraq": "D-IQ",
    "Delegation for relations with Iran": "D-IR",
    "Iran": "D-IR",
    "Delegation for relations with Japan": "D-JP",
    "Japan": "D-JP",
    "Delegation to the EU-Moldova Parliamentary Association Committee": "D-MD",
    "Delegation to the EU-Moldova Parliamentary Cooperation Committee": "D-MD",
    "Moldova": "D-MD",
    "Delegation to the EU-Montenegro Stabilisation and Association Parliamentary Committee": "D-ME",
    "Delegation to the EU-former Yugoslav Republic of Macedonia Joint Parliamentary Committee": "D-MK",
    "EU-Former Yugoslav Republic of Macedonia": "D-MK",
    "Delegation to the EU-Mexico Joint Parliamentary Committee": "D-MX",
    'Delegation for relations with the countries of South America': 'DSAM',
    'Delegation for relations with the countries of Central America and Mexico': 'DCAM',
    "EU-Mexico": "D-MX",
    "Delegation to the EU-Serbia Stabilisation and Association Parliamentary Committee": "D-RS",
    "Delegation to the EU-Russia Parliamentary Cooperation Committee": "D-RU",
    "Russia": "D-RU",
    'Delegation for relations with Russia': 'D-RU',
    "Delegation to the EU-Turkey Joint Parliamentary Committee": "D-TR",
    "EU-Turkey": "D-TR",
    "Delegation to the EU-Ukraine Parliamentary Association Committee": "D-UA",
    "Ukraine": "D-UA",
    "Delegation for relations with the United States": "D-US",
    "United States": "D-US",
    "Delegation for relations with South Africa": "D-ZA",
    "South Africa": "D-ZA",
    "Delegation to the ACP-EU Joint Parliamentary Assembly": "DACP",
    "Members from the European Parliament to the Joint Parliamentary Assembly of the Agreement between the African, Caribbean and Pacific States and the European Union (ACP-EU)": "DACP",
    "Andean Community": "DAND",
    "Delegation for relations with the countries of the Andean Community": "DAND",
    "Australia and New Zealand": "DANZ",
    "Delegation for relations with Australia and New Zealand": "DANZ",
    "Arab Peninsula": "DARP",
    "Delegation for relations with the Arab Peninsula": "DARP",
    "Delegation for relations with the countries of Southeast Asia and the Association of Southeast Asian Nations (ASEAN)": "DASE",
    "Southeast Asia, ASEAN": "DASE",
    "Central America": "DCAM",
    "Delegation for relations with the countries of Central America": "DCAM",
    "Cariforum – EU": "DCAR",
    "Delegation to the Cariforum-EU\xa0Parliamentary Committee": "DCAR",
    "Delegation to the Cariforum-EU Parliamentary Committee": "DCAR",
    "Delegation to the EU-Kazakhstan, EU-Kyrgyzstan, EU-Uzbekistan and EU-Tajikistan Parliamentary Cooperation Committees and for relations with Turkmenistan and Mongolia": "DCAS",
    "Kazakhstan, Kyrgyzstan, Uzbekistan, Tajikistan, Turkmenistan and Mongolia": "DCAS",
    "Delegation for relations with Switzerland and Norway and to the EU-Iceland Joint Parliamentary Committee and the European Economic Area (EEA) Joint Parliamentary Committee": "DEEA",
    "Delegation for relations with Switzerland, Iceland and Norway and to the European Economic Area (EEA) Joint Parliamentary Committee": "DEEA",
    "Switzerland, Iceland and Norway and European Economic Area (EEA)": "DEEA",
    "Switzerland, Norway and the EU-Iceland and EEA JPCs": "DEEA",
    "Delegation to the Euronest Parliamentary Assembly": "DEPA",
    "Gulf States, Yemen": "DGUL",
    "Delegation for relations with the Korean Peninsula": "DKOR",
    "Korean Peninsula": "DKOR",
    "Delegation to the Euro-Latin American Parliamentary Assembly": "DLAT",
    "Delegation for relations with the Maghreb countries and the Arab Maghreb Union": "DMAG",
    "Delegation for relations with the Maghreb countries and the Arab Maghreb Union (including Libya)": "DMAG",
    "Maghreb": "DMAG",
    "Delegation for relations with the Mashreq countries": "DMAS",
    "Mashreq": "DMAS",
    "Delegation to the Parliamentary Assembly of the Union for the Mediterranean": "DMED",
    "Delegation to the UfM Parliamentary Assembly": "DMED",
    "Delegation for relations with Mercosur": "DMER",
    "Mercosur": "DMER",
    "Delegation for relations with the NATO Parliamentary Assembly": "DNAT",
    "NATO": "DNAT",
    "Delegation for relations with Palestine": "DPAL",
    "Delegation for relations with the Pan-African Parliament": "DPAP",
    "Pan-African Parliament": "DPAP",
    "Palestinian Legislative Council": "DPLC",
    "Delegation for relations with the Palestinian Legislative Council": "DPLC",
    "Delegation for relations with the countries of South Asia": "DSAS",
    "Delegation for relations with the countries of South Asia and the South Asia Association for Regional Cooperation (SAARC)": "DSAS",
    "South Asia": "DSAS",
    "Armenia, Azerbaijan and Georgia": "DSCA",
    "Delegation to the EU-Armenia Parliamentary Partnership Committee, EU-Azerbaijan Parliamentary Cooperation Committee and the EU-Georgia Parliamentary Association Committee": "DSCA",
    "Albania, Bosnia and Herzegovina, Serbia, Montenegro, Kosovo": "DSEE",
    "Delegation for relations with Bosnia and Herzegovina, and Kosovo": "DSEE",
    "South-East Europe": "DSEE",
    "EEA": "EEA",
    "Estonia": "ESTO",
    "Hungary": "HUNG",
    "Latvia": "LATV",
    "Lithuania": "LITH",
    "Malta": "MALT",
    "Poland": "POLA",
    "Romania": "ROMA",
    "Delegation to the EU-Romania Joint Parliamentary Committee": "ROMA",
    "Russia": "RUSS",
    "South-East Europe": "SEE",
    "Switzerland, Iceland, Norway": "SIN",
    "Slovakia": "SLOA",
    "Slovenia": "SLOE",
    "Turkey": "TURK",
    "Ukraine, Moldova, Belarus": "UBM",
    "Delegation for relations with Estonia": u"",
    "Delegation for relations with Latvia": u"",
    "Delegation for relations with South-east Europe": u"",
    "Delegation for relations with Sweden, Finland, Iceland and the Nordic Council": u"",
    "Delegation for relations with the Czech Republic, the Slovak Republic and Slovenia": u"",
    "Delegation for relations with the Maghreb countries": u"",
    "Delegation for relations with the Mashreq countries and the Gulf": u"",
    "Delegations to the parliamentary cooperation committees and delegations for relations with Ukraine, Belarus and Moldova": u"",
    "Delegations to the parliamentary cooperation committees for relations with Armenia, Azerbaijan and Georgia": u"",
    "Delegation to the EC-Austria Joint Parliamentary Committee": u"",
    "Delegation to the EC-Norway Joint Parliamentary Committee": u"",
    "Delegation to the EC-Sweden Joint Parliamentary Committee": u"",
    "Delegation to the EU-Austria Joint Parliamentary Committee": u"",
    "Delegation to the EU-Norway Joint Parliamentary Committee": u"",
    "Delegation to the European Parliament/Portuguese Piarliament Joint Committee": u"",
    "Delegation to the EU-Sweden Joint Parliamentary Committee": u"",
    "Delegation for relations with Albania, Bulgaria and Romania": u"",
    "Delegation for relations with Bulgaria and Romania": u"",
    "Delegation for relations with Estonia, Lithuania and Latvia": u"",
    "Delegation for relations with Norway": u"",
    "Delegation for relations with Sweden": u"",
    "Delegation for relations with the countries of South Asia and the South Asian Association for Regional Cooperation (SAARC)": u"",
    "Delegation for relations with the Republics of the Commonwealth of Independent States (CIS)": u"",
    "Delegations to the parliamentary cooperation committees and delegations for relations with Kazakhstan, Kyrgyzstan, Uzbekistan, Tajikistan, Turkmenistan and Mongolia": u"",
    "Delegation to the EU-Kazakhstan, EU-Kyrgyzstan and EU-Uzbekistan Parliamentary Cooperation Committees and Delegation for relations with Tadjikistan, Turkmenistan and Mongolia": u"",
    "Delegation to the EC-European Economic Area Joint Parliamentary Committe": u"",
    "Delegation to the European Economic Area Joint Parliamentary Committee": u"",
    "Delegation to the EU-Ukraine and the EU-Moldova Parliamentary Cooperation Committees and Delegation for relations with Belarus": u"",
    "Delegation for relations with Czechoslovakia": u"",
    "Delegation for relations with Switzerland": u"",
    "Delegation for relations with Switzerland, Iceland and Norway": u"",
    "Delegation for relations with the Czech Republic and the Slovak Republic": u"",
    "Delegation to the EC-Malta Joint Parliamentary Committee": u"",
    "Delegation to the EU-Latvia Joint Parliamentary Committee": u"",
    "Delegation to the EU-Slovenia Joint Parliamentary Committee": u"",
    "Delegation for relations with Lithuania": u"",
    "Delegation for relations with the Mashreq countries and the Gulf States": u"",
    "Delegation for relations with the Member States of ASEAN and the ASEAN Interparliamentary Organisation (AIPO) and the Republic of Korea": u"",
    "Delegation for relations with the Member States of ASEAN, south-east Asia and the Republic of Korea": u"",
    "Delegation to the EC-Cyprus Joint Parliamentary Committee": u"",
    "Delegation to the EU-Estonia Joint Parliamentary Committee": u"",
    "Delegation to the EU-Slovak Republic Joint Parliamentary Committee": u"",
    "Delegation for relations with the Member States of ASEAN, South-east Asia and the Republic of Korea": u"",
    "Delegation to the EU-Malta Joint Parliamentary Committee": u"",
    "Delegation to the EU-Poland Joint Parliamentary Committee": u"",
    "Members from the European Parliament to the Joint Assembly of the Agreement between the African, Caribbean and Pacific States and the European Union (ACP-EU)": u"",
    "Delegation to the EU-Czech Republic Joint Parliamentary Committee": u"",
    "Delegation for relations with the countries of South America and MERCOSUR": u"",
    "Delegation to the EU-Hungary Joint Parliamentary Committee": u"",
    "Delegation to the EU-Lithuania Joint Parliamentary Committee": u"",
    "Delegation for relations with the Gulf States, including Yemen": u"",
    "Delegation to the EU-Former Yugoslav Republic of Macedonia Joint Parliamentary Committee": u"",
    "Delegation to the EU-Bulgaria Joint Parliamentary Committee": u"",
    "Delegation to the EU-Cyprus Joint Parliamentary Committee": u"",
    "Delegation for relations with the countries of south-east Europe": u"",
    "Delegation to the_Cariforum _ EU_Parliamentary Committee": u"",
    "Delegation to the European Economic Area Joint Parliamentary Committee (EEA)": u"",
    "Delegation for relations with the Mercosur countries": u"",
    "Delegation to the EU-Armenia, EU-Azerbaijan and EU-Georgia Parliamentary Cooperation Committees": u"",
    "Delegation to the Euro-Mediterranean Parliamentary Assembly": u"",
    "Delegation to the EU-Ukraine Parliamentary Cooperation Committee": u"",
    "Delegation to the EU-Kazakhstan, EU-Kyrgyzstan and EU-Uzbekistan Parliamentary Cooperation Committees, and for relations with Tajikistan, Turkmenistan and Mongolia": u"",
    "Delegation for relations with Albania, Bosnia and Herzegovina, Serbia, Montenegro and Kosovo": u"",

}

MEPS_ALIASES={
    4522: ["NICHOLSON OF WINTERBOURNE Baroness"],
    28246: ["ALVARO Alexander", "Alvaro"],
    1316: ["HARRISON Lyndon H.A."],
    2008: ["IZQUIERDO COLLADO Juan de Dios"],
    2076: ["LE GALLOU Jean-Yves R.R."],
    4427: ["POOS Jacques F."],
    1937: ["WILLOCKX Frederik A.A."],
    39709:["ZLOTEA MARIAN", 'Zlotea'],
    1385: ["SEAL Barry H."],
    1427: ["ADAM Gordon J."],
    2134: ["BELLERÉ Spalato"],
    1959: ["DARY Michel J.M."],
    1404: ["MCMAHON Hugh R."],
    1527: ["DOS SANTOS Manuel"],
    2219: ["SOUCHET Dominique F.C."],
    96776: ["THUN UND HOHENSTEIN Róża Gräfin von", "Thun und Hohenstein"],
    96958: ["(THE EARL OF) DARTMOUTH William", 'WilliAmendment (The Earl of) Dartmouth'],
    124874: ["PIECHA Bolesław G."],
    40599: ['PIETIKÄINEN Sirpa'],
    96864: ['SASSOLI David-Maria'],
    1466: ["HAPPART José H.G."],
    96745: ['Grčze', 'grcze'],
    28266: ["in'tveld", 'in`tveld'],
    96695: ['MORKŪNAITĖ Radvilė', 'morkūnaitė'],
    2237: ['Barthet-Mayer Christine', 'MUSTIN-MAYER Christine'],
    4433: ['Zappalà', "ZAPPALÀ Stefano"],
    4328: ['Obiols i Germà', 'Raimon Obiols i Germà'],
    28243: ['Chatzimartakis'],
    28577: ['Xenagiannakopoulou'],
    28220: ['Graessle', 'graessle'],
    2306: ['Virrankoski-Itälä'],
    28297: ['Saryus-Wolski'],
    4436: ['Pitella'],
    28226: ['Ehlert', 'Jan Christian Ehler'],
    1892: ['Coehlo', 'Coelho Carlo'],
    22861: ["O'Neachtain"],
    2001: ['Galeote Quecedo'],
    4238: ['Martin H.P.', 'mmHans-Peter Martin'],
    1403: ['D. Martin', 'Martin David W.'],
    28397: ['Díaz de Mera'],
    28407: ['Meyer Pleite', 'Willy Meyer Pleite'],
    28128: ['Carlshamre'],
    28345: ['Hammerstein Mintz'],
    4319: ['Ayuso González'],
    1253: ['Poettering'],
    4308: ['Vidal-Quadras Roca'],
    4550: ['Evans Jillian'],
    28342: ['Badia Cutchet'],
    96862: ['Briard Auconie', 'Sophie Briard Auconie'],
    28136: ['Barsi Pataky'],
    96861: ['Mihaylova', 'Nadezhda Mihaylova'],
    30099: ['Bernáthné Mohácsi'],
    34720: ['Wojciechowski Bernard Piotr'],
    28409: ['Romeva Rueda', 'Raьl Romeva i Rueda'],
    28156: ['Dan Jшrgensen'],
    96758: ['Haefner', 'Gerald Haefner'],
    2099: ['Evans Robert J.E.'],
    28242: ['Lambsdorff Graf'],
    23868: ['FLAŠÍKOVÁ BEŇOVÁ Monika', 'Flašíková Beňová'],
    34249: ['Husmenova', 'HYUSMENOVA, Filiz Hakaeva'],
    96709: ['Morten Lokkegaard'],
    28306: ['Ana Maria Gomes'],
    96811: ['Estarŕs Ferragut'],
    4266: ['Hedkvist Pedersen'],
    2182: ['M Trakatellis'],
    4469: ['Giovanni Claudio Fava'],
    24089: ['W. Tomczak'],
    23770: ['A. Peczak'],
    1249: ['Janis Sakellariou'],
    124933: ['Ceballos'],
    4379: ['Koldo Gorostiaga'],
    1418: ["COLLINS Kenneth D."],
    185974: ['Solé I Ferrando'],
    1432: ["D'ANCONA Hedy"],
    1282: ["OOSTLANDER Arie M."],
    1950: ["AELVOET Magda G.H."],
    96812: ["LÓPEZ AGUILAR Juan Fernando"],
    1120: ["JENSEN Kirsten M."],
    2021: ["CABROL Christian E.A."],
    1241: ["VAN PUTTEN Maartje J.A."],
    2148: ["AF UGGLAS Margaretha"],
    2202: ["D'ABOVILLE Gérard"],
    1474: ["DESAMA Claude J.-M.J."],
    1251: ["HERMANS Anna (An) M.A."],
    4548: ["MACCORMICK Professor Sir Neil"],
    4749: ["NISTICÒ Giuseppe"],
    1470: ["VANDEMEULEBROUCKE Jaak H.-A."],
    1974: ["SIERRA GONZÁLEZ Angela del Carmen"],
    2222: ["DES PLACES Edouard C.M.P."],
    28398: ["Iturgaiz Angulo"],
    4412: ['Mathieu'],
    96848: ['Nedelcheva'],
    96685: ['Manner'],
    97308: ['Savisaar', 'Vilja Savisaar'],
    30475: ['Vitkauskaite'],
    125065: ['Vozemberg'],
    125005: ['Nart Peñalver'],
    90110: ['PUNSET BANNEL'],
    125093: ['Papadakis Konstantinos'],
    4334: ['Valenciano Martínez-Orozco'],
    125032: ['Valcárcel'],
    125045: ['Aguilera García'],
    125038: ['Pagazaurtundúa Ruiz'],
    125033: ['Rodriguez-Rubio Vázquez'],
    125043: ['Rodríguez-Piñero Fernández'],
    4289: ['NIEBLER Angelika'],
    4533: ['Gill CBE'],
    4560: ['MANDERS Toine'],
    28273: ['Juknevičienė'],
    28291: ['Jordan Cizelj'],
    124776: ['Delvaux-Stehres'],
    21918: ['dos Santos'],
    124745: ['Grigule'],
    23413: ['Kleva'],
    98341: ['Paunova'],
    96999: ['Mirskis'],
    }

TITLES=[u'Sir',
        u'Lady',
        u'Baroness',
        u'Baron',
        u'Lord',
        u'Gräfin von',
        u'Earl',
        u'Duke',
        u'The Earl of',
        u'(The Earl of)',
        u'The Lord',
        u'Professor Doktor',
        u'Doktor Professor',
        u'Professor Sir',
        u'Professor',
]

VOTE_URL_TEMPLATES={
    # older are vote_nominaux style urls
    (6, '2004-12-16'): 'vn', (6, '2004-12-15'): 'vn', (6, '2004-12-14'): 'vn', (6, '2004-12-02'): 'vn', (6, '2004-12-01'): 'vn', (6, '2004-11-18'): 'vn',
    (6, '2004-11-17'): 'vn', (6, '2004-10-28'): 'vn', (6, '2004-10-26'): 'vn', (6, '2004-10-14'): 'vn', (6, '2004-09-16'): 'vn', (6, '2004-09-15'): 'vn',
    (6, '2005-12-15'): 'vn', (6, '2005-12-14'): 'vn', (6, '2005-12-13'): 'vn', (6, '2005-12-01'): 'vn', (6, '2005-11-17'): 'vn', (6, '2005-11-16'): 'vn',
    (6, '2005-11-15'): 'vn', (6, '2005-10-27'): 'vn', (6, '2005-10-26'): 'vn', (6, '2005-10-25'): 'vn', (6, '2005-10-13'): 'vn', (6, '2005-09-29'): 'vn',
    (6, '2005-09-28'): 'vn', (6, '2005-09-27'): 'vn', (6, '2005-09-08'): 'vn', (6, '2005-09-07'): 'vn', (6, '2005-09-06'): 'vn', (6, '2005-07-07'): 'vn',
    (6, '2005-07-06'): 'vn', (6, '2005-07-05'): 'vn', (6, '2005-07-04'): 'vn', (6, '2005-06-23'): 'vn', (6, '2005-06-09'): 'vn', (6, '2005-06-08'): 'vn',
    (6, '2005-06-07'): 'vn', (6, '2005-05-26'): 'vn', (6, '2005-05-12'): 'vn', (6, '2005-05-10'): 'vn', (6, '2005-05-09'): 'vn', (6, '2005-04-28'): 'vn',
    (6, '2005-04-14'): 'vn', (6, '2005-04-13'): 'vn', (6, '2005-04-12'): 'vn', (6, '2005-03-10'): 'vn', (6, '2005-03-09'): 'vn', (6, '2005-03-08'): 'vn',
    (6, '2005-02-24'): 'vn', (6, '2005-02-23'): 'vn', (6, '2005-02-22'): 'vn', (6, '2005-01-27'): 'vn', (6, '2005-01-13'): 'vn', (6, '2005-01-12'): 'vn',
    (6, '2005-01-11'): 'vn', (6, '2006-12-14'): 'vn', (6, '2006-12-13'): 'vn', (6, '2006-12-12'): 'vn', (6, '2006-11-30'): 'vn', (6, '2006-11-16'): 'vn',
    (6, '2006-11-15'): 'vn', (6, '2006-11-14'): 'vn', (6, '2006-10-26'): 'vn', (6, '2006-10-25'): 'vn', (6, '2006-10-24'): 'vn', (6, '2006-10-12'): 'vn',
    (6, '2006-09-28'): 'vn', (6, '2006-09-27'): 'vn', (6, '2006-09-26'): 'vn', (6, '2006-09-07'): 'vn', (6, '2006-09-06'): 'vn', (6, '2006-09-05'): 'vn',
    (6, '2006-07-06'): 'vn', (6, '2006-07-05'): 'vn', (6, '2006-07-04'): 'vn', (6, '2006-06-15'): 'vn', (6, '2006-06-14'): 'vn', (6, '2006-06-13'): 'vn',
    (6, '2006-06-01'): 'vn', (6, '2006-05-18'): 'vn', (6, '2006-05-17'): 'vn', (6, '2006-05-16'): 'vn', (6, '2006-04-27'): 'vn', (6, '2006-04-06'): 'vn',
    (6, '2006-04-05'): 'vn', (6, '2006-04-04'): 'vn', (6, '2006-03-23'): 'vn', (6, '2006-03-16'): 'vn', (6, '2006-03-15'): 'vn', (6, '2006-03-14'): 'vn',
    (6, '2006-02-16'): 'vn', (6, '2006-02-15'): 'vn', (6, '2006-02-14'): 'vn', (6, '2006-02-02'): 'vn', (6, '2006-01-19'): 'vn', (6, '2006-01-18'): 'vn',
    (6, '2006-01-17'): 'vn', (6, '2007-12-13'): 'vn', (6, '2007-12-12'): 'vn', (6, '2007-12-11'): 'vn', (6, '2007-11-29'): 'vn', (6, '2007-11-15'): 'vn',
    (6, '2007-11-14'): 'vn', (6, '2007-11-13'): 'vn', (6, '2007-10-25'): 'vn', (6, '2007-10-24'): 'vn', (6, '2007-10-23'): 'vn', (6, '2007-10-11'): 'vn',
    (6, '2007-09-27'): 'vn', (6, '2007-09-26'): 'vn', (6, '2007-09-25'): 'vn', (6, '2007-09-06'): 'vn', (6, '2007-09-05'): 'vn', (6, '2007-09-04'): 'vn',
    (6, '2007-07-12'): 'vn', (6, '2007-07-11'): 'vn', (6, '2007-07-10'): 'vn', (6, '2007-06-21'): 'vn', (6, '2007-06-20'): 'vn', (6, '2007-06-19'): 'vn',
    (6, '2007-06-07'): 'vn', (6, '2007-05-24'): 'vn', (6, '2007-05-23'): 'vn', (6, '2007-05-22'): 'vn', (6, '2007-05-10'): 'vn', (6, '2007-05-09'): 'vn',
    (6, '2007-04-26'): 'vn', (6, '2007-04-25'): 'vn', (6, '2007-04-24'): 'vn', (6, '2007-03-29'): 'vn', (6, '2007-03-15'): 'vn', (6, '2007-03-14'): 'vn',
    (6, '2007-03-13'): 'vn', (6, '2007-02-15'): 'vn', (6, '2007-02-14'): 'vn', (6, '2007-02-13'): 'vn', (6, '2007-02-01'): 'vn', (6, '2007-01-18'): 'vn',
    (6, '2008-12-18'): 'vn', (6, '2008-12-17'): 'vn', (6, '2008-12-16'): 'vn', (6, '2008-12-04'): 'vn', (6, '2008-11-20'): 'vn', (6, '2008-11-19'): 'vn',
    (6, '2008-11-18'): 'vn', (6, '2008-10-23'): 'vn', (6, '2008-10-22'): 'vn', (6, '2008-10-21'): 'vn', (6, '2008-10-09'): 'vn', (6, '2008-09-25'): 'vn',
    (6, '2008-09-24'): 'vn', (6, '2008-09-23'): 'vn', (6, '2008-09-04'): 'vn', (6, '2008-09-03'): 'vn', (6, '2008-09-02'): 'vn', (6, '2008-07-10'): 'vn',
    (6, '2008-07-09'): 'vn', (6, '2008-07-08'): 'vn', (6, '2008-07-07'): 'vn', (6, '2008-06-19'): 'vn', (6, '2008-06-18'): 'vn', (6, '2008-06-17'): 'vn',
    (6, '2008-06-05'): 'vn', (6, '2008-05-22'): 'vn', (6, '2008-05-21'): 'vn', (6, '2008-05-20'): 'vn', (6, '2008-05-08'): 'vn', (6, '2008-04-24'): 'vn',
    (6, '2008-04-23'): 'vn', (6, '2008-04-22'): 'vn', (6, '2008-04-10'): 'vn', (6, '2008-04-09'): 'vn', (6, '2008-03-13'): 'vn', (6, '2008-03-12'): 'vn',
    (6, '2008-03-11'): 'vn', (6, '2008-02-21'): 'vn', (6, '2008-02-20'): 'vn', (6, '2008-02-19'): 'vn', (6, '2008-02-18'): 'vn', (6, '2008-01-31'): 'vn',
    (6, '2008-01-16'): 'vn', (6, '2008-01-14'): 'vn', (6, '2009-05-07'): 'vn', (6, '2009-05-05'): 'vn', (6, '2009-05-04'): 'vn', (6, '2009-04-24'): 'vn',
    (6, '2009-04-21'): 'vn', (6, '2009-03-26'): 'vn', (6, '2009-03-24'): 'vn', (6, '2009-03-12'): 'vn', (6, '2009-03-09'): 'vn', (6, '2009-02-19'): 'vn',
    (6, '2009-02-18'): 'vn', (6, '2009-02-05'): 'vn', (6, '2009-02-04'): 'vn', (6, '2009-02-03'): 'vn', (6, '2009-01-15'): 'vn', (6, '2009-01-14'): 'vn',
    (6, '2009-01-13'): 'vn', (7, '2009-12-17'): 'vn', (7, '2009-12-16'): 'vn', (7, '2009-12-15'): 'vn', (7, '2009-12-14'): 'vn', (7, '2009-11-26'): 'vn',
    (7, '2009-11-24'): 'vn', (7, '2009-11-12'): 'vn', (7, '2009-10-22'): 'vn', (7, '2009-10-21'): 'vn', (7, '2009-10-20'): 'vn', (7, '2009-10-19'): 'vn',
    (7, '2009-10-08'): 'vn', (7, '2009-10-07'): 'vn', (7, '2009-09-17'): 'vn', (7, '2009-09-16'): 'vn', (7, '2009-09-15'): 'vn', (7, '2009-09-14'): 'vn',
    (7, '2010-12-15'): 'vn', (7, '2010-12-14'): 'vn', (7, '2010-11-25'): 'vn', (7, '2010-11-23'): 'vn', (7, '2010-11-11'): 'vn', (7, '2010-10-21'): 'vn',
    (7, '2010-10-19'): 'vn', (7, '2010-10-07'): 'vn', (7, '2010-09-22'): 'vn', (7, '2010-09-21'): 'vn', (7, '2010-09-09'): 'vn', (7, '2010-09-08'): 'vn',
    (7, '2010-09-07'): 'vn', (7, '2010-07-08'): 'vn', (7, '2010-07-07'): 'vn', (7, '2010-06-17'): 'vn', (7, '2010-06-16'): 'vn', (7, '2010-06-15'): 'vn',
    (7, '2010-05-20'): 'vn', (7, '2010-05-19'): 'vn', (7, '2010-05-18'): 'vn', (7, '2010-05-06'): 'vn', (7, '2010-03-25'): 'vn', (7, '2010-03-11'): 'vn',
    (7, '2010-03-10'): 'vn', (7, '2010-03-09'): 'vn', (7, '2010-03-08'): 'vn', (7, '2010-02-25'): 'vn', (7, '2010-02-11'): 'vn', (7, '2010-02-09'): 'vn',
    (7, '2010-02-08'): 'vn', (7, '2010-01-21'): 'vn', (7, '2010-01-20'): 'vn', (7, '2011-12-15'): 'vn', (7, '2011-12-14'): 'vn', (7, '2011-12-13'): 'vn',
    (7, '2011-12-01'): 'vn', (7, '2011-11-17'): 'vn', (7, '2011-11-16'): 'vn', (7, '2011-11-15'): 'vn', (7, '2011-10-27'): 'vn', (7, '2011-10-25'): 'vn',
    (7, '2011-10-13'): 'vn', (7, '2011-09-29'): 'vn', (7, '2011-09-28'): 'vn', (7, '2011-09-27'): 'vn', (7, '2011-09-15'): 'vn', (7, '2011-09-14'): 'vn',
    (7, '2011-09-13'): 'vn', (7, '2011-07-07'): 'vn', (7, '2011-07-06'): 'vn', (7, '2011-06-09'): 'vn', (7, '2011-06-07'): 'vn', (7, '2011-05-12'): 'vn',
    (7, '2011-04-07'): 'vn', (7, '2011-04-05'): 'vn', (7, '2011-03-24'): 'vn', (7, '2011-03-23'): 'vn', (7, '2011-03-10'): 'vn', (7, '2011-03-09'): 'vn',
    (7, '2011-02-17'): 'vn', (7, '2011-02-16'): 'vn', (7, '2011-02-15'): 'vn', (7, '2011-02-03'): 'vn', (7, '2011-01-20'): 'vn', (7, '2011-01-19'): 'vn',
    (7, '2011-01-18'): 'vn', (7, '2012-12-13'): 'vn', (7, '2012-12-12'): 'vn', (7, '2012-12-11'): 'vn', (7, '2012-11-22'): 'vn', (7, '2012-11-21'): 'vn',
    (7, '2012-11-20'): 'vn', (7, '2012-10-26'): 'vn', (7, '2012-10-25'): 'vn', (7, '2012-09-13'): 'vn', (7, '2012-09-12'): 'vn', (7, '2012-09-11'): 'vn',
    (7, '2012-07-05'): 'vn', (7, '2012-07-04'): 'vn', (7, '2012-07-03'): 'vn', (7, '2012-06-14'): 'vn', (7, '2012-06-12'): 'vn', (7, '2012-05-24'): 'vn',
    (7, '2012-05-23'): 'vn', (7, '2012-05-22'): 'vn', (7, '2012-04-20'): 'vn', (7, '2012-04-19'): 'vn', (7, '2012-04-18'): 'vn', (7, '2012-03-29'): 'vn',
    (7, '2012-03-15'): 'vn', (7, '2012-03-14'): 'vn', (7, '2012-02-16'): 'vn', (7, '2012-02-15'): 'vn', (7, '2012-02-14'): 'vn', (7, '2012-02-02'): 'vn',
    (7, '2012-01-19'): 'vn', (7, '2012-01-18'): 'vn', (7, '2013-12-11'): 'vn', (7, '2013-12-10'): 'vn', (7, '2013-11-18'): 'vn', (7, '2013-10-24'): 'vn',
    (7, '2013-10-23'): 'vn', (7, '2013-10-22'): 'vn', (7, '2013-10-10'): 'vn', (7, '2013-10-09'): 'vn', (7, '2013-09-10'): 'vn', (7, '2013-07-02'): 'vn',
    (7, '2013-06-13'): 'vn', (7, '2013-06-12'): 'vn', (7, '2013-05-23'): 'vn', (7, '2013-05-22'): 'vn', (7, '2013-04-18'): 'vn', (7, '2013-04-16'): 'vn',
    (7, '2013-03-14'): 'vn', (7, '2013-03-12'): 'vn', (7, '2013-02-06'): 'vn', (7, '2013-02-05'): 'vn', (7, '2013-01-17'): 'vn', (7, '2013-01-16'): 'vn',
    (7, '2013-01-15'): 'vn', (7, '2014-02-27'): 'vn', (7, '2014-02-06'): 'vn', (7, '2014-01-16'): 'vn',
    # starting from the 8th term the liste_presence style urls are our source
    (7, '2010-07-07'): 'lp', (7, '2010-07-06'): 'lp', # these should be really 'vn'
    (8, '2014-12-18'): 'lp', (8, '2014-12-17'): 'lp', (8, '2014-12-16'): 'lp', (8, '2014-11-27'): 'lp', (8, '2014-11-26'): 'lp', (8, '2014-11-25'): 'lp',
    (8, '2014-11-13'): 'lp', (8, '2014-10-23'): 'lp', (8, '2014-10-22'): 'lp', (8, '2014-10-21'): 'lp', (8, '2014-09-18'): 'lp', (8, '2014-09-17'): 'lp',
    (8, '2014-09-16'): 'lp', (8, '2014-07-17'): 'lp', (8, '2014-07-16'): 'lp', (8, '2015-12-17'): 'lp', (8, '2015-12-16'): 'lp', (8, '2015-12-15'): 'lp',
    (8, '2015-12-02'): 'lp', (8, '2015-11-26'): 'lp', (8, '2015-11-25'): 'lp', (8, '2015-11-24'): 'lp', (8, '2015-11-11'): 'lp', (8, '2015-10-29'): 'lp',
    (8, '2015-10-28'): 'lp', (8, '2015-10-27'): 'lp', (8, '2015-10-14'): 'lp', (8, '2015-10-08'): 'lp', (8, '2015-10-07'): 'lp', (8, '2015-10-06'): 'lp',
    (8, '2015-09-17'): 'lp', (8, '2015-09-16'): 'lp', (8, '2015-09-10'): 'lp', (8, '2015-09-09'): 'lp', (8, '2015-09-08'): 'lp', (8, '2015-07-09'): 'lp',
    (8, '2015-07-08'): 'lp', (8, '2015-07-07'): 'lp', (8, '2015-06-24'): 'lp', (8, '2015-06-11'): 'lp', (8, '2015-06-10'): 'lp', (8, '2015-06-09'): 'lp',
    (8, '2015-05-27'): 'lp', (8, '2015-05-21'): 'lp', (8, '2015-05-20'): 'lp', (8, '2015-05-19'): 'lp', (8, '2015-04-30'): 'lp', (8, '2015-04-29'): 'lp',
    (8, '2015-04-28'): 'lp', (8, '2015-04-27'): 'lp', (8, '2015-04-15'): 'lp', (8, '2015-03-25'): 'lp', (8, '2015-03-12'): 'lp', (8, '2015-03-11'): 'lp',
    (8, '2015-03-10'): 'lp', (8, '2015-02-12'): 'lp', (8, '2015-02-11'): 'lp', (8, '2015-01-15'): 'lp', (8, '2015-01-13'): 'lp', (8, '2016-12-15'): 'lp',
    (8, '2016-12-14'): 'lp', (8, '2016-12-13'): 'lp', (8, '2016-12-01'): 'lp', (8, '2016-11-24'): 'lp', (8, '2016-11-23'): 'lp', (8, '2016-11-22'): 'lp',
    (8, '2016-11-21'): 'lp', (8, '2016-10-27'): 'lp', (8, '2016-10-26'): 'lp', (8, '2016-10-25'): 'lp', (8, '2016-10-06'): 'lp', (8, '2016-10-05'): 'lp',
    (8, '2016-10-04'): 'lp', (8, '2016-10-03'): 'lp', (8, '2016-09-15'): 'lp', (8, '2016-09-14'): 'lp', (8, '2016-09-13'): 'lp', (8, '2016-09-12'): 'lp',
    (8, '2016-07-07'): 'lp', (8, '2016-07-06'): 'lp', (8, '2016-07-05'): 'lp', (8, '2016-07-04'): 'lp', (8, '2016-06-28'): 'lp', (8, '2016-06-23'): 'lp',
    (8, '2016-06-09'): 'lp', (8, '2016-06-08'): 'lp', (8, '2016-06-07'): 'lp', (8, '2016-06-06'): 'lp', (8, '2016-05-26'): 'lp', (8, '2016-05-25'): 'lp',
    (8, '2016-05-10'): 'lp', (8, '2016-04-14'): 'lp', (8, '2016-04-13'): 'lp', (8, '2016-04-12'): 'lp', (8, '2016-03-10'): 'lp', (8, '2016-03-09'): 'lp',
    (8, '2016-03-08'): 'lp', (8, '2016-03-07'): 'lp', (8, '2016-02-25'): 'lp', (8, '2016-02-04'): 'lp', (8, '2016-02-03'): 'lp', (8, '2016-02-02'): 'lp',
    (8, '2016-02-01'): 'lp', (8, '2016-01-21'): 'lp', (8, '2016-01-20'): 'lp', (8, '2016-01-19'): 'lp', (8, '2017-12-14'): 'lp', (8, '2017-12-13'): 'lp',
    (8, '2017-12-12'): 'lp', (8, '2017-11-30'): 'lp', (8, '2017-11-16'): 'lp', (8, '2017-11-15'): 'lp', (8, '2017-11-14'): 'lp', (8, '2017-11-13'): 'lp',
    (8, '2017-10-26'): 'lp', (8, '2017-10-25'): 'lp', (8, '2017-10-24'): 'lp', (8, '2017-10-23'): 'lp', (8, '2017-10-05'): 'lp', (8, '2017-10-04'): 'lp',
    (8, '2017-10-03'): 'lp', (8, '2017-09-14'): 'lp', (8, '2017-09-13'): 'lp', (8, '2017-09-12'): 'lp', (8, '2017-07-06'): 'lp', (8, '2017-07-05'): 'lp',
    (8, '2017-07-04'): 'lp', (8, '2017-07-03'): 'lp', (8, '2017-06-15'): 'lp', (8, '2017-06-14'): 'lp', (8, '2017-06-13'): 'lp', (8, '2017-06-01'): 'lp',
    (8, '2017-05-18'): 'lp', (8, '2017-05-17'): 'lp', (8, '2017-05-16'): 'lp', (8, '2017-04-27'): 'lp', (8, '2017-04-26'): 'lp', (8, '2017-04-06'): 'lp',
    (8, '2017-04-05'): 'lp', (8, '2017-04-04'): 'lp', (8, '2017-04-03'): 'lp', (8, '2017-03-16'): 'lp', (8, '2017-03-15'): 'lp', (8, '2017-03-14'): 'lp',
    (8, '2017-03-13'): 'lp', (8, '2017-03-02'): 'lp', (8, '2017-02-16'): 'lp', (8, '2017-02-15'): 'lp', (8, '2017-02-14'): 'lp', (8, '2017-02-02'): 'lp',
    (8, '2017-01-19'): 'lp', (8, '2018-12-13'): 'lp', (8, '2018-12-12'): 'lp', (8, '2018-12-11'): 'lp', (8, '2018-12-10'): 'lp', (8, '2018-11-29'): 'lp',
    (8, '2018-11-28'): 'lp', (8, '2018-11-15'): 'lp', (8, '2018-11-14'): 'lp', (8, '2018-11-13'): 'lp', (8, '2018-11-12'): 'lp', (8, '2018-10-25'): 'lp',
    (8, '2018-10-24'): 'lp', (8, '2018-10-23'): 'lp', (8, '2018-10-22'): 'lp', (8, '2018-10-04'): 'lp', (8, '2018-10-03'): 'lp', (8, '2018-10-02'): 'lp',
    (8, '2018-10-01'): 'lp', (8, '2018-09-13'): 'lp', (8, '2018-09-12'): 'lp', (8, '2018-09-11'): 'lp', (8, '2018-09-10'): 'lp', (8, '2018-07-05'): 'lp',
    (8, '2018-07-04'): 'lp', (8, '2018-07-03'): 'lp', (8, '2018-07-02'): 'lp', (8, '2018-06-14'): 'lp', (8, '2018-06-13'): 'lp', (8, '2018-06-12'): 'lp',
    (8, '2018-06-11'): 'lp', (8, '2018-05-31'): 'lp', (8, '2018-05-30'): 'lp', (8, '2018-05-29'): 'lp', (8, '2018-05-28'): 'lp', (8, '2018-05-03'): 'lp',
    (8, '2018-05-02'): 'lp', (8, '2018-04-19'): 'lp', (8, '2018-04-18'): 'lp', (8, '2018-04-17'): 'lp', (8, '2018-04-16'): 'lp', (8, '2018-03-15'): 'lp',
    (8, '2018-03-14'): 'lp', (8, '2018-03-13'): 'lp', (8, '2018-03-01'): 'lp', (8, '2018-02-28'): 'lp', (8, '2018-02-08'): 'lp', (8, '2018-02-07'): 'lp',
    (8, '2018-02-06'): 'lp', (8, '2018-01-18'): 'lp', (8, '2018-01-17'): 'lp', (8, '2018-01-16'): 'lp', (8, '2018-01-15'): 'lp', (8, '2019-04-18'): 'lp',
    (8, '2019-04-17'): 'lp', (8, '2019-04-16'): 'lp', (8, '2019-04-15'): 'lp', (8, '2019-04-04'): 'lp', (8, '2019-04-03'): 'lp', (8, '2019-03-28'): 'lp',
    (8, '2019-03-27'): 'lp', (8, '2019-03-26'): 'lp', (8, '2019-03-25'): 'lp', (8, '2019-03-14'): 'lp', (8, '2019-03-13'): 'lp', (8, '2019-03-12'): 'lp',
    (8, '2019-03-11'): 'lp', (8, '2019-02-14'): 'lp', (8, '2019-02-13'): 'lp', (8, '2019-02-12'): 'lp', (8, '2019-02-11'): 'lp', (8, '2019-01-31'): 'lp',
    (8, '2019-01-30'): 'lp', (8, '2019-01-17'): 'lp', (8, '2019-01-16'): 'lp', (8, '2019-01-15'): 'lp', (8, '2019-01-14'): 'lp',
    # refound votes
    (7, '2014-04-15'): 'lp', (7, '2014-04-17'): 'lp', (8, '2016-05-11'): 'lp', (8, '2016-05-12'): 'lp'}


# these dossiers have been scraped previously, but have been split into
# multiple ones, the references have one added letter in front of the (type)
# designator usually A-Z
SPLIT_DOSSIERS = {
    '1991/2118(INS)', '1992/2223(INS)', '1994/2195(INI)', '1995/2078(INI)', '1995/2189(INI)', '1996/2143(INI)', '1997/2015(INI)', '1997/2044(INI)', '1998/2041(INI)',
    '1998/2077(INI)', '1998/2078(INI)', '1998/2101(INI)', '1998/2165(INI)', '1999/2010(INS)', '1999/2184(INI)', '2000/2126(INI)', '2000/2323(INI)', '2001/2061(INI)',
    '2001/2069(INI)', '2002/2264(INI)', '2003/2004(INI)', '2003/2057(INI)', '2003/2107(INI)', '2004/2125(INI)', '2005/2122(INI)', '2005/2138(IMM)', '2005/2148(INI)',
    '2005/2176(IMM)', '2006/2013(INI)', '2006/2014(INI)', '2006/2015(INI)', '2006/2059(INI)', '2007/0181(CNS)', '2008/2093(IMM)', '2008/2117(INI)', '2008/2121(INI)',
    '2009/2029(REG)', '2009/2134(INL)', '2009/2170(INI)', '2009/2239(INI)', '2009/2816(RSP)', '2010/2073(INI)', '2011/0341(COD)', '2011/0901(COD)', '2011/2176(INI)',
    '2011/2184(INI)', '2011/2257(REG)', '2011/2304(IMM)', '2012/0033(NLE)', '2012/0219(NLE)', '2012/2012(REG)', '2012/2024(INI)', '2012/2061(INI)', '2012/2146(IMM)',
    '2012/2241(IMM)', '2012/2260(INI)', '2012/2274(IMM)', '2012/2303(INI)', '2012/2309(INI)', '2012/2317(INI)', '2012/2324(INI)', '2012/2686(RSP)', '2012/2807(RSP)',
    '2012/2817(RSP)', '2012/2863(RSP)', '2012/2899(RSP)', '2013/0120(NLE)', '2013/0151(NLE)', '2013/0267(NLE)', '2013/2046(INI)', '2013/2089(INI)', '2013/2102(INI)',
    '2013/2129(INI)', '2013/2167(INI)', '2013/2171(INI)', '2013/2184(INI)', '2013/2191(IMM)', '2013/2271(IMM)', '2013/2280(IMM)', '2013/2692(RSP)', '2013/2739(RSP)',
    '2013/2847(RPS)', '2013/2887(RSP)', '2014/2009(INI)', '2014/2034(IMM)', '2014/2227(IMM)', '2014/2536(RSP)', '2014/2557(RSO)', '2014/2604(RSP)', '2014/3015(RSP)',
    '2015/2009(INI)', '2015/2073(IMM)', '2015/2081(INI)', '2015/2594(RSP)', '2015/2600(RSP)', '2015/2659(RSP)', '2015/2901(RSP)', '2015/2996(RSP)', '2015/3029(RSP)',
    '2016/0357(COD)', '2016/0360(COD)', '2016/2031(INI)', '2016/2040(IMM)', '2016/2069(IMM)', '2016/2205(DEC)', '2016/2661(RSP)', '2017/2034(IMM)', '2017/2062(IMM)',
    '2017/2205(INL)', '2017/2207(INI)', '2017/2264(REG)', '2017/2595(RSP)', '2017/2657(RSP)', '2017/2836(RSP)', '2017/2872(RSP)', '2017/2902(RSP)', '2018/0330(COD)',
    '2018/2002(INL)', '2018/2027(IMM)', '2018/2033(INI)', '2018/2087(INI)', '2018/2154(INI)', '2018/2917(RSP)', '2018/2921(RSP)'
}

VOTE_DOX = {
    'A-0244/2006': '2006/0093(CNS)',
    'C6-0036/2005': '2005/0005(CNS)',
    'C6-0334/2006': '2006/0168(CNS)',
    'B6/0266/2007': '2007/2577(RSP)',
    'C6-0081/2009': '2009/0029(CNS)',
    'C6-0270/2008': '2008/0144(CNS)',
    'C7-0223/2009': '2009/0152(CNS)',
    'C8-0271/2015': '2015/0209(NLE)',
    'A6-04110/2007': '2006/0086(COD)',
    'A7/0011/2009': '2009/0802(CNS)',
    'B50169/2004': '2004/2612(RSP)',
    'B6-00250/2006': '2006/2553(RSP)',
    'B6 0460/2006': '2006/2614(RSP)',
    'A6/0070/2006': '2005/0137(AVC)',
    'C6-0111/2006': '2006/0055(CNS)',
}

VOTE_DOX_RE = {
    'A6-170/2008': '2008/0065(CNS)',
    'A6-247/2007': '2007/2023(INI)',
    'A6-265/2006': '2006/0002(CNS)',
    'A6-310/2007': '2007/0086(CNS)',
    'A6-353/2008': '2008/2166(BUD)',
    'B6-206/2007': '2007/2564(RSP)',
    'B6-387/2006': '2006/2592(RSP)',
    'A6-0120/2009': '2016/0280(COD)',
}

stage2percent = {
    'Legislative proposal published': 0,
    'Initial legislative proposal published': 0,
    'Modified legislative proposal published': 0,
    'Legislative proposal': 0,
    'Commission preliminary draft budget published': 0,

    'Preparatory phase in Parliament': 3,

    'Commission draft budget published': 5,
    'Council draft budget published': 5,
    'Committee referral announced in Parliament, 1st reading/single reading': 5,
    'Committee referral announced in Parliament, 2nd reading': 5,
    'Referral to joint committee announced in Parliament': 5,

    'Amended legislative proposal for reconsultation published': 10,
    'Referral to associated committees announced in Parliament': 10,
    'Awaiting Parliament 1st reading / single reading / budget 1st stage': 10,
    'Awaiting Parliament 2nd reading': 10,

    'Formal reconsultation of Parliament': 20,

    'Vote in committee, 1st reading/single reading': 25,
    'Vote in committee, 2nd reading': 25,
    'Vote scheduled in committee, 1st reading/single reading': 25,
    'Awaiting approval of interim report': 25,
    'Awaiting reconsultation': 25,

    'Committee interim report tabled for plenary': 30,
    'Start of budgetary conciliation (Parliament and Council)': 30,

    'Committee report tabled for plenary, single reading': 40,
    'Committee report tabled for plenary, 1st reading/single reading': 40,
    "Preparatory budgetary report tabled for plenary": 40,
    'Budgetary report tabled for plenary, 1st reading': 40,
    'Budgetary report tabled for plenary, 2nd reading': 40,
    'Budgetary conciliation report tabled for plenary': 40,
    'Decision by committee, without report': 40,
    "Committee report tabled for plenary, reconsultation": 40,
    'Report tabled for plenary, 3rd reading': 40,
    "Committee report tabled for plenary confirming Parliament's position": 40,
    'Committee recommendation tabled for plenary, 2nd reading': 40,
    'Formal meeting of Conciliation Committee': 40,

    'Indicative plenary sitting date, 1st reading/single reading': 50,
    'Indicative plenary sitting date, 2nd reading': 50,
    'Debate in Parliament': 50,
    'Debate scheduled': 50,
    'Debate in plenary scheduled': 50,

    'Results of vote in Parliament': 60,
    'Vote in plenary scheduled': 60,
    'Vote scheduled': 60,

    'Decision by Parliament, 1st reading/single reading': 65,
    'Decision by Parliament, 2nd reading': 65,
    'Decision by Parliament, 3rd reading': 65,

    "Matter referred back to the committee responsible": 70,
    'Report referred back to committee': 70,
    'Awaiting committee decision': 70,
    'Awaiting the opening of interinstitutional negotiations': 70,

    "Committee decision to open interinstitutional negotiations with report adopted in committee": 75,
    "Committee decision to open interinstitutional negotiations after 1st reading in Parliament": 75,
    "Rejection by committee to open interinstitutional negotiations with report adopted in committee": 75,
    "Committee decision to open interinstitutional negotiations prior to the adoption of the report": 75,
    "Committee decision to open interinstitutional negotiations at 2nd reading": 75,
    'Commission response to text adopted in plenary': 75,

    'Interinstitutional negotiations opened - proposal for mandate approved': 77,

    "Approval in committee of the text agreed at 1st reading interinstitutional negotiations": 80,
    "Approval in committee of the text agreed at early 2nd reading interinstitutional negotiations": 80,

    'Budgetary conciliation committee convened': 85,
    "Approval in committee of the text agreed at 2nd reading interinstitutional negotiations": 85,
    'Awaiting announcement of budgetary joint text': 85,
    'Awaiting final decision': 85,

    'Awaiting Council 1st reading position / budgetary conciliation convocation': 87,
    'Awaiting Council decision on budgetary joint text': 87,
    'Awaiting Council decision on delegated act': 87,
    'Awaiting Council decision, 2nd reading': 87,
 
    'Political agreement in Council on its 1st reading position': 90,
    'Budgetary joint text published': 90, # ?
    "Parliament's amendments rejected by Council": 90,
    "Delegated act not objected by Council": 90,
    "Delegated act not objected by Parliament": 90,
    "Delegated act objected by Council": 90,
    'Decision by Council': 90,
    'Final decision by Conciliation Committee': 90,
    'Decision by Council, 3rd reading': 90,
    'Awaiting Parliament decision on budgetary joint text': 90,

    'Council position published': 91,

    "Council amended draft budget published": 92, #?
    'Final act signed': 92,
    'Draft budget approved by Council': 92,
    'Act approved by Council, 2nd reading': 92,
    'Joint text approved by Conciliation Committee co-chairs': 92,
    'Agreement not reached in budgetary conciliation': 92,
    'Political agreement on Council position': 92,
    'Provisional agreement between Parliament and Council on final act': 92,

    'Council position scheduled for adoption': 93,
    'Amended budget adopted by Council': 93,

    'Act adopted by Council after consultation of Parliament': 94,
    "Act adopted by Council after Parliament's 1st reading": 94,
    'Awaiting signature of act': 94,

    'Final act signed by Parliament and Council': 95,

    'End of procedure in Parliament': 96,

    'Proposal withdrawn by Commission': 100,
    'Final act published in Official Journal': 100,
    'Procedure lapsed or withdrawn': 100,
    'Procedure rejected': 100,
    'Procedure completed': 100,
    'Procedure completed - delegated act enters into force': 100,
    'Procedure completed - delegated act rejected': 100,
    'Procedure completed, awaiting publication in Official Journal': 100,

 }

ACTIVITY_MAP={'CRE': 'plenary speeches',
        "REPORT": 'reports',
        "REPORT-SHADOW": 'shadow reports',
        "COMPARL": 'opinions',
        "COMPARL-SHADOW": 'shadow opinions',
        "COMPARL-LEG": "legal basis opinions",
        "MOTION": 'institutional motions',
        "OQ": 'oral questions',
        'WEXP': 'written explanations',
        'MINT': 'major interpellations',
        "WQ": 'written questions',
        "IMOTION": 'individual motions',
        "amendments": 'amendments',
        "WDECL": 'written declarations'}
