#!/usr/bin/env python
# -*- coding: utf-8 -*-
#    This file is part of parltrack

#    parltrack is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    parltrack is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.

#    You should have received a copy of the GNU Affero General Public License
#    along with parltrack  If not, see <http://www.gnu.org/licenses/>.

# (C) 2011 by Stefan Marsiske, <stefan.marsiske@gmail.com>, Asciimoo

COMMITTEE_MAP={'AFET': "Foreign Affairs",
               'DROI': "Human Rights",
               'SEDE': "Security and Defence",
               'DEVE': "Development",
               'INTA': "International Trade",
               'BUDG': "Budgets",
               'CONT': "Budgetary Control",
               'CODE': "Conciliation Committee",
               'ECON': "Economic and Monetary Affairs",
               'EMPL': "Employment and Social Affairs",
               'ENVI': "Environment, Public Health and Food Safety",
               'ITRE': "Industry, Research and Energy",
               'IMCO': "Internal Market and Consumer Protection",
               'TRAN': "Transport and Tourism",
               'REGI': "Regional Development",
               'AGRI': "Agriculture and Rural Development",
               'PECH': "Fisheries",
               'CULT': "Culture and Education",
               'JURI': "Legal Affairs",
               'LIBE': "Civil Liberties, Justice and Home Affairs",
               'AFCO': "Constitutional Affairs",
               'FEMM': "Women's Rights and Gender Equality",
               'PETI': "Petitions",
               'CRIS': "Financial, Economic and Social Crisis",
               'SURE': "Policy Challenges Committee",
               'Foreign Affairs': 'AFET',
               'Human Rights': 'DROI',
               'Security and Defence': 'SEDE',
               'Development': 'DEVE',
               'International Trade': 'INTA',
               'Budgets': 'BUDG',
               'Budgetary Control': 'CONT',
               'Economic and Monetary Affairs': 'ECON',
               'Employment and Social Affairs': 'EMPL',
               'Environment, Public Health and Food Safety': 'ENVI',
               'Industry, Research and Energy': 'ITRE',
               'Internal Market and Consumer Protection': 'IMCO',
               'Transport and Tourism': 'TRAN',
               'Regional Development': 'REGI',
               'Agriculture and Rural Development': 'AGRI',
               'Fisheries': 'PECH',
               'Culture and Education': 'CULT',
               'Legal Affairs': 'JURI',
               'Civil Liberties, Justice and Home Affairs': 'LIBE',
               'Constitutional Affairs': 'AFCO',
               "Women's Rights and Gender Equality": 'FEMM',
               u"Women’s Rights and Gender Equality": 'FEMM',
               'Petitions': 'PETI',
               'Financial, Economic and Social Crisis': 'CRIS',
               'Policy Challenges Committee': 'SURE',
               'Committee on Foreign Affairs': 'AFET',
               'Committee on Human Rights': 'DROI',
               'Committee on Security and Defence': 'SEDE',
               'Committee on Development': 'DEVE',
               'Committee on International Trade': 'INTA',
               'Committee on Budgets': 'BUDG',
               'Committee on Budgetary Control': 'CONT',
               'Committee on Economic and Monetary Affairs': 'ECON',
               'Committee on Employment and Social Affairs': 'EMPL',
               'Committee on Environment, Public Health and Food Safety': 'ENVI',
               'Committee on Industry, Research and Energy': 'ITRE',
               'Committee on Internal Market and Consumer Protection': 'IMCO',
               'Committee on the Internal Market and Consumer Protection': 'IMCO',
               'Committee on Transport and Tourism': 'TRAN',
               'Committee on Regional Development': 'REGI',
               'Committee on Agriculture and Rural Development': 'AGRI',
               'Committee on Fisheries': 'PECH',
               'Committee on Culture and Education': 'CULT',
               'Committee on Legal Affairs': 'JURI',
               'Committee on Civil Liberties, Justice and Home Affairs': 'LIBE',
               'Committee on Constitutional Affairs': 'AFCO',
               "Committee on Women's Rights and Gender Equality": 'FEMM',
               'Committee on Petitions': 'PETI',
               'Committee on Financial, Economic and Social Crisis': 'CRIS',
               'Committee on Policy Challenges Committee': 'SURE'}

STAGEMAP = {'Preparatory phase in Parliament': '01. Preparatory phase in EP',
            'Awaiting Parliament 1st reading / single reading / budget 1st stage': '02. EP 1st reading',
            'Awaiting Council 1st reading position / budgetary conciliation convocation': '03. EC 1st reading position',
            'Awaiting reconsultation': '04. Awaiting reconsultation',
            'Awaiting Parliament decision after Council rejection of joint text': '05. EP decision after EC rejection of joint text',
            'Awaiting Council decision, blocked at 1st reading': '06. EC decision, blocked at 1st reading',
            'Awaiting Parliament 2nd reading': '07. EP 2nd reading',
            'Awaiting Council decision, 2nd reading': '08. EC decision, 2nd reading',
            'Awaiting Parliament and Council decision, 3rd reading': '09. EP and EC decision, 3rd reading',
            'Conciliation ongoing': '10. Conciliation ongoing',
            'Political agreement on final act': '11. Political agreement on final act',
            'Awaiting signature': '12. Awaiting signature',
            'Awaiting final decision': '13. Awaiting final decision',}

STAGES = ['Preparatory phase in Parliament',
          'Awaiting Parliament 1st reading / single reading / budget 1st stage',
          'Awaiting reconsultation',
          'Awaiting Council decision, blocked at 1st reading',
          'Awaiting Council 1st reading position / budgetary conciliation convocation',
          'Budgetary conciliation committee convened',
          'Awaiting announcement of budgetary joint text',
          'Awaiting budgetary conciliation report',
          'Awaiting Parliament decision on budgetary joint text',
          'Awaiting Council decision on budgetary joint text',
          'Awaiting Parliament decision after Council rejection of joint text',
          'Awaiting Parliament 2nd reading',
          'Awaiting Council decision, 2nd reading',
          'Conciliation ongoing',
          'Conciliation ended',
          'Awaiting Parliament and Council decision, 3rd reading',
          'Political agreement on final act',
          'Awaiting signature',
          'Awaiting final decision',
          'Procedure completed, awaiting publication in Official Journal']

ALL_STAGES= [ "Preparatory phase in Parliament",
              "Awaiting Parliament 1st reading / single reading / budget 1st stage",
              "Awaiting reconsultation",
              "Awaiting Council decision, blocked at 1st reading",
              "Awaiting Council 1st reading position / budgetary conciliation convocation",
              "Budgetary conciliation committee convened",
              "Awaiting announcement of budgetary joint text",
              "Awaiting budgetary conciliation report",
              "Awaiting Parliament decision on budgetary joint text",
              "Awaiting Council decision on budgetary joint text",
              "Awaiting Parliament decision after Council rejection of joint text",
              "Awaiting Parliament 2nd reading",
              "Awaiting Council decision, 2nd reading",
              "Conciliation ongoing",
              "Conciliation ended",
              "Awaiting Parliament and Council decision, 3rd reading",
              "Political agreement on final act",
              "Awaiting signature",
              "Awaiting final decision",
              "Procedure completed, awaiting publication in Official Journal",
              "Procedure completed",
              "Procedure rejected",
              "Procedure lapsed or withdrawn"]

buildings={ u"Altiero Spinelli": 'ASP',
            u"Willy Brandt": 'WIB',
            u"Paul-Henri Spaak": 'PHS',
            u"Atrium": "ATR",
            u"Louise Weiss": 'LOW',
            u"Winston Churchill": 'WIC',
            u"Bât. Altiero Spinelli": 'ASP',
            u"Bât. Willy Brandt": 'WIB',
            u"Bât. Paul-Henri Spaak": 'PHS',
            u"Bât. Atrium": "ATR",
            u"Bât. Louise Weiss": 'LOW',
            u"Bât. Winston Churchill": 'WIC',
            }

ipexevents={u'CSL 1R Agreement': {'body': 'CSL', 'oeil': 'Council meeting', },
            u'CSL Common Position': {'body': 'CSL', 'oeil': 'Council position', },
            u'CSL Final Adoption': {'body': 'CSL',},
            u'CSL Final Agreement': {'body': 'CSL',},
            u'CSL Non Acceptance': {'body': 'CSL',},
            u'Date': {'body': 'EP', 'oeil': 'Commission/Council: initial legislative document', },
            u'Deadline Amendments': {'body': 'EP',},
            u'EP 1R Committee': {'body': 'EP', 'oeil': 'EP: decision of the committee responsible, 1st reading/single reading', },
            u'EP 1R Plenary': {'body': 'EP', 'oeil': 'EP: position, 1st reading or single reading', },
            u'EP 2R Committee': {'body': 'EP', 'oeil': 'EP: decision of the committee responsible, 2nd reading', },
            u'EP 2R Plenary': {'body': 'EP', 'oeil': 'EP: position, 2nd reading', },
            u'EP 3R Plenary': {'body': 'EP', 'oeil': 'EP: legislative resolution, 3rd reading', },
            u'EP Conciliation Committee': {'body': 'EP', 'oeil': 'Results of conciliation', },
            u'EP officialisation': {'body': 'EP', 'oeil': 'Commission/Council: initial legislative document', },
            u'End Date': {'body': 'EP', 'oeil': 'Final legislative act', },
            u'Foreseen CSL Activities': {'body': 'CSL',},
            u'Prev Adopt in Cte': {'body': 'EP',},
            u'Prev DG PRES': {'body': 'EC'},
            }
